accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^login', views.LoginView.as_view(), name='login'),
    url(r'^logout', views.LogoutView.as_view(), name='logout'),
    url(r'^staff-login-prompt', views.staff_login_prompt, name='staff-login-prompt'),
    url(r'^edit-profile', views.EditProfileView.as_view(), name='edit-profile'),
]

api/urls.py
from django.conf.urls import include, url
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name = 'api'

urlpatterns = [
    url(r'^entries/$', views.DictionaryEntryList.as_view(), name='entries'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

edictweb/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^accounts/', include('accounts.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^importer/', include('importer.urls')),
    url(r'^(?:searcher/)?', include('searcher.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

		<link rel="stylesheet" type="text/css" href="{% static "style.css" %}">

		{% block head %}
		{% endblock %}
	</head>
	<body>
		<div class="float-right">
			{% if request.user.is_authenticated %}
				<a href="{% url 'accounts:edit-profile' %}"><img style="width: 30px; height: 30px" src="{{ profile.get_image_or_default_url }}" alt="Profile Image"/>
				Logged in as {{ request.user.username }}
				{% if profile.display_name %}({{ profile.display_name }}){% endif %}
				</a> / <a href="{% url 'accounts:logout' %}">Logout</a>
			{% endif %}
		</div>

		<div class="container">
			<h1><a id="home-link" href="/">edictweb</a></h1>

			{% block body %}
			{% endblock %}
		</div>

		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
	</body>
</html>